import os

def generate_markdown_plan():
    content = """# 🚀 POS System Integration Plan: Lowell Nails & Spa

## 1. Vision & Core Objectives
Transform the existing scheduling/CRM system into a high-performance Point of Sale (POS) ecosystem. This bridges the gap between **Scheduled Intent** and **Financial Completion**.

## 2. Technical Architecture (Postgres Expansion)
To support currency flow, we need to implement a deterministic ledger.

### New Database Tables
| Table | Purpose |
| :--- | :--- |
| `transactions` | Records the "Who, When, and How Much" of every sale. |
| `line_items` | Breaks down exactly what was sold (Service vs. Retail). |
| `products` | Inventory management for retail items (polish, oils). |
| `gift_cards` | Stored value management and balance tracking. |

## 3. Implementation Roadmap

### Phase 1: The Payment Engine (Core)
- **Stripe Terminal Integration:** Support for physical card readers at the front desk.
- **Checkout UI:** A React modal that triggers when an appointment is marked "Done."
- **Automated Tax/Tip:** Michigan 6% tax calculation and 15/18/20/25% tip suggestions.

### Phase 2: Operations & Payroll
- **Commission Logic:** Auto-calculate the 60/40 or 50/50 splits defined in `business.config.js`.
- **SMS Receipts:** Use existing Twilio integration to send digital receipts.
- **Inventory Alerts:** Michael sends an SMS when retail stock is low.

### Phase 3: Michael (AI) Intelligence
- **Gift Card Balance Tool:** Michael can answer "How much is left on my card?"
- **Pricing Queries:** Michael references the structured price list to give quotes.
- **Daily Close-Out:** Michael can summarize the day's revenue for the owner at 7:00 PM.

## 4. Modified `business.config.js` Requirements
We need to extend the configuration to handle financial defaults:
```javascript
module.exports = {
  currency: "USD",
  taxRate: 0.06,
  tipSuggestions: [15, 18, 20, 25],
  staff: [
    { name: "Cyrus", commission: 0.60 }, 
    // ... etc
  ]
}
```

## 5. Success Metrics
1. **Zero Data Leakage:** Every dollar in the drawer matches a line item in Postgres.
2. ** Michael Autonomy:** AI handles 100% of gift card and pricing inquiries.
3. **Frictionless Checkout:** Transaction completion in under 3 clicks on the iPad.

---
*Document generated by the POS Planning Tool*
"""
    
    output_path = os.path.join(os.getcwd(), "POS_INTEGRATION_SPEC.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"✅ Success: Technical Spec generated at {output_path}")

if __name__ == "__main__":
    generate_markdown_plan()